--- 
- hosts: webservers
  become: yes

  vars: 
    html_loc: "/Users/madams/Documents/lab/stelligent/index.html"
    html_dest: "/var/www/html/index.html"

  tasks: 
    - name: Install apache2
      apt: pkg=apache2 state=installed update_cache=true
      register: apache2installed
      notify:
       - Start apache2

    - name: Create index
      when: apache2installed|success
      copy: src="{{ html_loc }}"  dest="{{ html_dest }}"  mode=755  owner=root group=root
      notify:
        - Restart apache2

    - action: uri url=http://localhost return_content=yes
      register: webpage

    - fail: msg='web content not loaded properly'
      when: "'Automation for the People' not in webpage.content"

  handlers:
    - name: Start apache2
      service: name=apache2 state=started

    - name: Restart apache2
      service: name=apache2 state=restarted

    - name: reload apache2
      service: name=apache2 state=reloaded

